# -*- coding: utf-8 -*-
"""Fraud_Detection_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRYvR_VFHB5523nvbV-asM4CGZhZLT7_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_recall_curve,
    roc_auc_score,
    average_precision_score
)

from xgboost import XGBClassifier

df = pd.read_csv("/content/Fraud.csv")

# Log amount
df['log_amount'] = np.log1p(df['amount'])

# Transaction timing
df['hour'] = df['step'] % 24

# Behavioral signals
df['isLargeAmount'] = (df['amount'] > 200000).astype(int)

# Origin account risk indicators
df['origBalanceZero'] = (df['oldbalanceOrg'] == 0).astype(int)

# Fraud-prone transaction types
df['isTransfer'] = (df['type'] == 'TRANSFER').astype(int)
df['isCashOut'] = (df['type'] == 'CASH_OUT').astype(int)

# Drop leakage & ID columns
df.drop([
    'nameOrig',
    'nameDest',
    'newbalanceOrig',
    'newbalanceDest'
], axis=1, inplace=True)

train = df[df['step'] <= 600]
test  = df[df['step'] > 600]

X_train = train.drop('isFraud', axis=1)
y_train = train['isFraud']

X_test = test.drop('isFraud', axis=1)
y_test = test['isFraud']

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features = ['type']
numerical_features = X_train.columns.drop('type')

preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
    ('num', 'passthrough', numerical_features)
])

from xgboost import XGBClassifier

scale_weight = (len(y_train) - y_train.sum()) / y_train.sum()

model = XGBClassifier(
    n_estimators=150,
    max_depth=5,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_weight,
    eval_metric='logloss',
    random_state=42
)

from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', model)
])

pipeline.fit(X_train, y_train)

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.show()

from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

y_pred = pipeline.predict(X_test)
y_prob = pipeline.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("PR-AUC:", average_precision_score(y_test, y_prob))